/* eslint-env serviceworker */
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ---------------------------------------------------------
// Workbox Routing Logic (Migrated from vite.config.js)
// ---------------------------------------------------------

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
);

// AI Chat - Network Only
registerRoute(
  /\/api\/ai\/chat/i,
  new NetworkOnly()
);

// API requests - Network First
registerRoute(
  /\/api\/.*/i,
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5 // 5 minutes
      })
    ]
  })
);

// ---------------------------------------------------------
// Push Notifications Logic
// ---------------------------------------------------------

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'Runli';
    const options = {
      body: data.message || 'You have a new notification.',
      icon: '/icon-192.png',
      badge: '/vite.svg',
      vibrate: [200, 100, 200],
      data: {
        link: data.link || '/',
        id: data.id || null
      },
      actions: data.actions || []
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (error) {
    console.error('Error parsing push data:', error);
    event.waitUntil(
      self.registration.showNotification('Runli', {
        body: event.data.text() || 'New Notification',
        icon: '/icon-192.png'
      })
    );
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = new URL(event.notification.data.link || '/', self.location.origin).href;

  // Track the click interaction if an ID was provided
  if (event.notification.data.id) {
    event.waitUntil(
      fetch('/api/notifications/track', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: event.notification.data.id, action: 'clicked' })
      }).catch(err => console.error('Failed to track notification click', err))
    );
  }

  // Handle actions (e.g. Snooze, Logged, Dismiss)
  if (event.action) {
    // Basic implementation for actions.
    if (event.action === 'dismiss') {
      return;
    }
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, check if any window is open and navigate it
      if (windowClients.length > 0 && 'navigate' in windowClients[0]) {
        windowClients[0].focus();
        return windowClients[0].navigate(urlToOpen);
      }
      // Otherwise, open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

self.addEventListener('notificationclose', (event) => {
  // Track dismissal
  if (event.notification.data && event.notification.data.id) {
    event.waitUntil(
      fetch('/api/notifications/track', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: event.notification.data.id, action: 'dismissed' })
      }).catch(err => console.error('Failed to track notification dismissal', err))
    );
  }
});
